### ISSUE TITLE
units_compatible does not take pint.Unit as arguments type

### ISSUE THREAD

**Issue by nollety** [leroyvn/pinttrs#1]
The signature of `units_compatible()` says that its arguments must be of type `pint.Unit`, however the following code:
```python
import pint
from pinttr.util import units_compatible

units_compatible(pint.Unit("m"), pint.Unit("km"))
```
raises
```python
AttributeError: 'Unit' object has no attribute '_get_non_multiplicative_units'
```
whereas:
```python
ureg = pint.UnitRegistry()
units_compatible(ureg("m"), ureg("km"))
```
works fine, which suggests that the arguments type of `units_compatible()` is `pint.Quantity`, instead of `pint.Unit`?

**Comment by leroyvn** [comment]
`ureg("m")` and `ureg("km")` are both `pint.Unit` instances with registry `ureg`. If you check the Pint docs, you'll find out that you actually should never use `pint.Unit` or `pint.Quantity` right on; instead, you must create them from a registry.

So my answer is: you simply should not do something like `units_compatible(pint.Unit("m"), pint.Unit("km"))`.

**Comment by leroyvn** [comment]
To be more concrete, this will raise the exception you mentioned as well:
```python
1. * pint.Unit("m")
```

**Comment by nollety** [comment]
Ah, I'm sorry, I have not read that part of the Pint docs... Thank you for the explanation!
